my.props.p1= confprop from application.* used in same module component
my.props.p2= confprop from application.* used in diff module component
my.props.p3= not used conf property
prop.for.bean = prop from application.* used in bean class from same module
prop.for.component = prop from application.* used in component from same module
# marked as not used if the module is used as library
prop.for.b-bean1 = prop from application.* used in bean class from diff module defined as bean in main
prop.for.b-bean2 = prop from application.* used in bean class from diff module defined as bean there
# not resolved:
spring.config.import=classpath:b-application.properties
