my.a.props.p1= confprop defined in A module set in A application.* used in same (A) module component
my.a.props.p2= confprop defined in A module set in A application.* used in diff (B) module component
my.a.props.p3= not used conf property
prop.for.bean = prop defined and set in A application.* used in bean class from same (A) module
prop.for.component = prop defined and set in A application.* used in component from same (A) module
# marked as not used if the module is used as library
prop.for.b-bean1 = prop from application.* used in bean class from diff module defined as bean in main
prop.for.b-bean2 = prop from application.* used in bean class from diff module defined as bean there

my.b.props.prop1= confprop defined in B module set in A application.* used in (A) module component
my.b.props.prop2= confprop defined in B module set in A application.* used in (B) module component
my.test.props.prop2=confprop defined in A module Tests set in A main application.* used in same (A) module test

# not resolved:
spring.config.import=classpath:b-application.properties
